//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the franka_ros_controllers package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __franka_ros_controllers__JOINT_CONTROLLER_PARAMSCONFIG_H__
#define __franka_ros_controllers__JOINT_CONTROLLER_PARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace franka_ros_controllers
{
  class joint_controller_paramsConfigStatics;

  class joint_controller_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(joint_controller_paramsConfig &config, const joint_controller_paramsConfig &max, const joint_controller_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const joint_controller_paramsConfig &config1, const joint_controller_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, joint_controller_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const joint_controller_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, joint_controller_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const joint_controller_paramsConfig &config) const = 0;
      virtual void getValue(const joint_controller_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T joint_controller_paramsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T joint_controller_paramsConfig::* field;

      virtual void clamp(joint_controller_paramsConfig &config, const joint_controller_paramsConfig &max, const joint_controller_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const joint_controller_paramsConfig &config1, const joint_controller_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, joint_controller_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const joint_controller_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, joint_controller_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const joint_controller_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const joint_controller_paramsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, joint_controller_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, joint_controller_paramsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(joint_controller_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("position_joint_delta_filter"==(*_i)->name){position_joint_delta_filter = boost::any_cast<double>(val);}
        if("velocity_joint_delta_filter"==(*_i)->name){velocity_joint_delta_filter = boost::any_cast<double>(val);}
      }
    }

    double position_joint_delta_filter;
double velocity_joint_delta_filter;

    bool state;
    std::string name;

    class CONTROLLER_GAINS
{
  public:
    CONTROLLER_GAINS()
    {
      state = true;
      name = "Controller_Gains";
    }

    void setParams(joint_controller_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("j1_k"==(*_i)->name){j1_k = boost::any_cast<double>(val);}
        if("j2_k"==(*_i)->name){j2_k = boost::any_cast<double>(val);}
        if("j3_k"==(*_i)->name){j3_k = boost::any_cast<double>(val);}
        if("j4_k"==(*_i)->name){j4_k = boost::any_cast<double>(val);}
        if("j5_k"==(*_i)->name){j5_k = boost::any_cast<double>(val);}
        if("j6_k"==(*_i)->name){j6_k = boost::any_cast<double>(val);}
        if("j7_k"==(*_i)->name){j7_k = boost::any_cast<double>(val);}
        if("j1_d"==(*_i)->name){j1_d = boost::any_cast<double>(val);}
        if("j2_d"==(*_i)->name){j2_d = boost::any_cast<double>(val);}
        if("j3_d"==(*_i)->name){j3_d = boost::any_cast<double>(val);}
        if("j4_d"==(*_i)->name){j4_d = boost::any_cast<double>(val);}
        if("j5_d"==(*_i)->name){j5_d = boost::any_cast<double>(val);}
        if("j6_d"==(*_i)->name){j6_d = boost::any_cast<double>(val);}
        if("j7_d"==(*_i)->name){j7_d = boost::any_cast<double>(val);}
      }
    }

    double j1_k;
double j2_k;
double j3_k;
double j4_k;
double j5_k;
double j6_k;
double j7_k;
double j1_d;
double j2_d;
double j3_d;
double j4_d;
double j5_d;
double j6_d;
double j7_d;

    bool state;
    std::string name;

    
}controller_gains;

}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double position_joint_delta_filter;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velocity_joint_delta_filter;
//#line 20 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j1_k;
//#line 21 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j2_k;
//#line 22 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j3_k;
//#line 23 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j4_k;
//#line 24 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j5_k;
//#line 25 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j6_k;
//#line 26 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j7_k;
//#line 28 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j1_d;
//#line 29 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j2_d;
//#line 30 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j3_d;
//#line 31 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j4_d;
//#line 32 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j5_d;
//#line 33 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j6_d;
//#line 34 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      double j7_d;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("joint_controller_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const joint_controller_paramsConfig &__max__ = __getMax__();
      const joint_controller_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const joint_controller_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const joint_controller_paramsConfig &__getDefault__();
    static const joint_controller_paramsConfig &__getMax__();
    static const joint_controller_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const joint_controller_paramsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void joint_controller_paramsConfig::ParamDescription<std::string>::clamp(joint_controller_paramsConfig &config, const joint_controller_paramsConfig &max, const joint_controller_paramsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class joint_controller_paramsConfigStatics
  {
    friend class joint_controller_paramsConfig;

    joint_controller_paramsConfigStatics()
    {
joint_controller_paramsConfig::GroupDescription<joint_controller_paramsConfig::DEFAULT, joint_controller_paramsConfig> Default("Default", "", 0, 0, true, &joint_controller_paramsConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_joint_delta_filter = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_joint_delta_filter = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_joint_delta_filter = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("position_joint_delta_filter", "double", 0, "Filter parameter that dictates how smoothly subsequent joint position commands are smoothed. Also responsible for speed of joint position execution.", "", &joint_controller_paramsConfig::position_joint_delta_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("position_joint_delta_filter", "double", 0, "Filter parameter that dictates how smoothly subsequent joint position commands are smoothed. Also responsible for speed of joint position execution.", "", &joint_controller_paramsConfig::position_joint_delta_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velocity_joint_delta_filter = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velocity_joint_delta_filter = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velocity_joint_delta_filter = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("velocity_joint_delta_filter", "double", 0, "Filter parameter that dictates how smoothly subsequent joint velocity commands are smoothed. Also responsible for acceleration of joints.", "", &joint_controller_paramsConfig::velocity_joint_delta_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("velocity_joint_delta_filter", "double", 0, "Filter parameter that dictates how smoothly subsequent joint velocity commands are smoothed. Also responsible for acceleration of joints.", "", &joint_controller_paramsConfig::velocity_joint_delta_filter)));
joint_controller_paramsConfig::GroupDescription<joint_controller_paramsConfig::DEFAULT::CONTROLLER_GAINS, joint_controller_paramsConfig::DEFAULT> Controller_Gains("Controller_Gains", "", 0, 1, true, &joint_controller_paramsConfig::DEFAULT::controller_gains);
//#line 20 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j1_k = 200.0;
//#line 20 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j1_k = 1500.0;
//#line 20 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j1_k = 1200.0;
//#line 20 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j1_k", "double", 0, "Stiffness parameter of joint 1", "", &joint_controller_paramsConfig::j1_k)));
//#line 20 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j1_k", "double", 0, "Stiffness parameter of joint 1", "", &joint_controller_paramsConfig::j1_k)));
//#line 21 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j2_k = 200.0;
//#line 21 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j2_k = 1500.0;
//#line 21 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j2_k = 1000.0;
//#line 21 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j2_k", "double", 0, "Stiffness parameter of joint 2", "", &joint_controller_paramsConfig::j2_k)));
//#line 21 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j2_k", "double", 0, "Stiffness parameter of joint 2", "", &joint_controller_paramsConfig::j2_k)));
//#line 22 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j3_k = 200.0;
//#line 22 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j3_k = 1500.0;
//#line 22 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j3_k = 1000.0;
//#line 22 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j3_k", "double", 0, "Stiffness parameter of joint 3", "", &joint_controller_paramsConfig::j3_k)));
//#line 22 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j3_k", "double", 0, "Stiffness parameter of joint 3", "", &joint_controller_paramsConfig::j3_k)));
//#line 23 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j4_k = 200.0;
//#line 23 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j4_k = 1500.0;
//#line 23 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j4_k = 800.0;
//#line 23 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j4_k", "double", 0, "Stiffness parameter of joint 4", "", &joint_controller_paramsConfig::j4_k)));
//#line 23 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j4_k", "double", 0, "Stiffness parameter of joint 4", "", &joint_controller_paramsConfig::j4_k)));
//#line 24 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j5_k = 100.0;
//#line 24 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j5_k = 1000.0;
//#line 24 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j5_k = 300.0;
//#line 24 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j5_k", "double", 0, "Stiffness parameter of joint 5", "", &joint_controller_paramsConfig::j5_k)));
//#line 24 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j5_k", "double", 0, "Stiffness parameter of joint 5", "", &joint_controller_paramsConfig::j5_k)));
//#line 25 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j6_k = 75.0;
//#line 25 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j6_k = 500.0;
//#line 25 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j6_k = 200.0;
//#line 25 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j6_k", "double", 0, "Stiffness parameter of joint 6", "", &joint_controller_paramsConfig::j6_k)));
//#line 25 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j6_k", "double", 0, "Stiffness parameter of joint 6", "", &joint_controller_paramsConfig::j6_k)));
//#line 26 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j7_k = 20.0;
//#line 26 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j7_k = 200.0;
//#line 26 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j7_k = 50.0;
//#line 26 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j7_k", "double", 0, "Stiffness parameter of joint 7", "", &joint_controller_paramsConfig::j7_k)));
//#line 26 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j7_k", "double", 0, "Stiffness parameter of joint 7", "", &joint_controller_paramsConfig::j7_k)));
//#line 28 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j1_d = 0.0;
//#line 28 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j1_d = 200.0;
//#line 28 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j1_d = 50.0;
//#line 28 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j1_d", "double", 0, "Damping parameter of joint 1", "", &joint_controller_paramsConfig::j1_d)));
//#line 28 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j1_d", "double", 0, "Damping parameter of joint 1", "", &joint_controller_paramsConfig::j1_d)));
//#line 29 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j2_d = 0.0;
//#line 29 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j2_d = 200.0;
//#line 29 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j2_d = 50.0;
//#line 29 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j2_d", "double", 0, "Damping parameter of joint 2", "", &joint_controller_paramsConfig::j2_d)));
//#line 29 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j2_d", "double", 0, "Damping parameter of joint 2", "", &joint_controller_paramsConfig::j2_d)));
//#line 30 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j3_d = 0.0;
//#line 30 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j3_d = 200.0;
//#line 30 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j3_d = 50.0;
//#line 30 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j3_d", "double", 0, "Damping parameter of joint 3", "", &joint_controller_paramsConfig::j3_d)));
//#line 30 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j3_d", "double", 0, "Damping parameter of joint 3", "", &joint_controller_paramsConfig::j3_d)));
//#line 31 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j4_d = 0.0;
//#line 31 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j4_d = 200.0;
//#line 31 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j4_d = 20.0;
//#line 31 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j4_d", "double", 0, "Damping parameter of joint 4", "", &joint_controller_paramsConfig::j4_d)));
//#line 31 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j4_d", "double", 0, "Damping parameter of joint 4", "", &joint_controller_paramsConfig::j4_d)));
//#line 32 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j5_d = 0.0;
//#line 32 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j5_d = 200.0;
//#line 32 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j5_d = 20.0;
//#line 32 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j5_d", "double", 0, "Damping parameter of joint 5", "", &joint_controller_paramsConfig::j5_d)));
//#line 32 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j5_d", "double", 0, "Damping parameter of joint 5", "", &joint_controller_paramsConfig::j5_d)));
//#line 33 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j6_d = 0.0;
//#line 33 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j6_d = 200.0;
//#line 33 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j6_d = 20.0;
//#line 33 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j6_d", "double", 0, "Damping parameter of joint 6", "", &joint_controller_paramsConfig::j6_d)));
//#line 33 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j6_d", "double", 0, "Damping parameter of joint 6", "", &joint_controller_paramsConfig::j6_d)));
//#line 34 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __min__.j7_d = 0.0;
//#line 34 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __max__.j7_d = 200.0;
//#line 34 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __default__.j7_d = 10.0;
//#line 34 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      Controller_Gains.abstract_parameters.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j7_d", "double", 0, "Damping parameter of joint 7", "", &joint_controller_paramsConfig::j7_d)));
//#line 34 "/home/ntnghia1999/dynamics_final/src/franka_ros_interface/franka_ros_controllers/cfg/joint_controller_params.cfg"
      __param_descriptions__.push_back(joint_controller_paramsConfig::AbstractParamDescriptionConstPtr(new joint_controller_paramsConfig::ParamDescription<double>("j7_d", "double", 0, "Damping parameter of joint 7", "", &joint_controller_paramsConfig::j7_d)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Controller_Gains.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr(new joint_controller_paramsConfig::GroupDescription<joint_controller_paramsConfig::DEFAULT::CONTROLLER_GAINS, joint_controller_paramsConfig::DEFAULT>(Controller_Gains)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr(new joint_controller_paramsConfig::GroupDescription<joint_controller_paramsConfig::DEFAULT::CONTROLLER_GAINS, joint_controller_paramsConfig::DEFAULT>(Controller_Gains)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr(new joint_controller_paramsConfig::GroupDescription<joint_controller_paramsConfig::DEFAULT, joint_controller_paramsConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<joint_controller_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    joint_controller_paramsConfig __max__;
    joint_controller_paramsConfig __min__;
    joint_controller_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const joint_controller_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static joint_controller_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &joint_controller_paramsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const joint_controller_paramsConfig &joint_controller_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const joint_controller_paramsConfig &joint_controller_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const joint_controller_paramsConfig &joint_controller_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<joint_controller_paramsConfig::AbstractParamDescriptionConstPtr> &joint_controller_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<joint_controller_paramsConfig::AbstractGroupDescriptionConstPtr> &joint_controller_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const joint_controller_paramsConfigStatics *joint_controller_paramsConfig::__get_statics__()
  {
    const static joint_controller_paramsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = joint_controller_paramsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __JOINT_CONTROLLER_PARAMSRECONFIGURATOR_H__
