//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the panda_joint_trajectory_action package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __panda_joint_trajectory_action__PANDAPOSITIONFFJOINTTRAJECTORYACTIONSERVERCONFIG_H__
#define __panda_joint_trajectory_action__PANDAPOSITIONFFJOINTTRAJECTORYACTIONSERVERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace panda_joint_trajectory_action
{
  class PandaPositionFFJointTrajectoryActionServerConfigStatics;

  class PandaPositionFFJointTrajectoryActionServerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(PandaPositionFFJointTrajectoryActionServerConfig &config, const PandaPositionFFJointTrajectoryActionServerConfig &max, const PandaPositionFFJointTrajectoryActionServerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PandaPositionFFJointTrajectoryActionServerConfig &config1, const PandaPositionFFJointTrajectoryActionServerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PandaPositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PandaPositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PandaPositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PandaPositionFFJointTrajectoryActionServerConfig &config) const = 0;
      virtual void getValue(const PandaPositionFFJointTrajectoryActionServerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PandaPositionFFJointTrajectoryActionServerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PandaPositionFFJointTrajectoryActionServerConfig::* field;

      virtual void clamp(PandaPositionFFJointTrajectoryActionServerConfig &config, const PandaPositionFFJointTrajectoryActionServerConfig &max, const PandaPositionFFJointTrajectoryActionServerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PandaPositionFFJointTrajectoryActionServerConfig &config1, const PandaPositionFFJointTrajectoryActionServerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PandaPositionFFJointTrajectoryActionServerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PandaPositionFFJointTrajectoryActionServerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PandaPositionFFJointTrajectoryActionServerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PandaPositionFFJointTrajectoryActionServerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PandaPositionFFJointTrajectoryActionServerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PandaPositionFFJointTrajectoryActionServerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PandaPositionFFJointTrajectoryActionServerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PandaPositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PandaPositionFFJointTrajectoryActionServerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("goal_time"==(*_i)->name){goal_time = boost::any_cast<double>(val);}
        if("stopped_velocity_tolerance"==(*_i)->name){stopped_velocity_tolerance = boost::any_cast<double>(val);}
        if("panda_joint1_goal"==(*_i)->name){panda_joint1_goal = boost::any_cast<double>(val);}
        if("panda_joint2_goal"==(*_i)->name){panda_joint2_goal = boost::any_cast<double>(val);}
        if("panda_joint3_goal"==(*_i)->name){panda_joint3_goal = boost::any_cast<double>(val);}
        if("panda_joint4_goal"==(*_i)->name){panda_joint4_goal = boost::any_cast<double>(val);}
        if("panda_joint5_goal"==(*_i)->name){panda_joint5_goal = boost::any_cast<double>(val);}
        if("panda_joint6_goal"==(*_i)->name){panda_joint6_goal = boost::any_cast<double>(val);}
        if("panda_joint7_goal"==(*_i)->name){panda_joint7_goal = boost::any_cast<double>(val);}
        if("panda_joint1_trajectory"==(*_i)->name){panda_joint1_trajectory = boost::any_cast<double>(val);}
        if("panda_joint2_trajectory"==(*_i)->name){panda_joint2_trajectory = boost::any_cast<double>(val);}
        if("panda_joint3_trajectory"==(*_i)->name){panda_joint3_trajectory = boost::any_cast<double>(val);}
        if("panda_joint4_trajectory"==(*_i)->name){panda_joint4_trajectory = boost::any_cast<double>(val);}
        if("panda_joint5_trajectory"==(*_i)->name){panda_joint5_trajectory = boost::any_cast<double>(val);}
        if("panda_joint6_trajectory"==(*_i)->name){panda_joint6_trajectory = boost::any_cast<double>(val);}
        if("panda_joint7_trajectory"==(*_i)->name){panda_joint7_trajectory = boost::any_cast<double>(val);}
      }
    }

    double goal_time;
double stopped_velocity_tolerance;
double panda_joint1_goal;
double panda_joint2_goal;
double panda_joint3_goal;
double panda_joint4_goal;
double panda_joint5_goal;
double panda_joint6_goal;
double panda_joint7_goal;
double panda_joint1_trajectory;
double panda_joint2_trajectory;
double panda_joint3_trajectory;
double panda_joint4_trajectory;
double panda_joint5_trajectory;
double panda_joint6_trajectory;
double panda_joint7_trajectory;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_time;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stopped_velocity_tolerance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint1_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint2_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint3_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint4_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint5_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint6_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint7_goal;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint1_trajectory;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint2_trajectory;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint3_trajectory;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint4_trajectory;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint5_trajectory;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint6_trajectory;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double panda_joint7_trajectory;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PandaPositionFFJointTrajectoryActionServerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PandaPositionFFJointTrajectoryActionServerConfig &__max__ = __getMax__();
      const PandaPositionFFJointTrajectoryActionServerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PandaPositionFFJointTrajectoryActionServerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PandaPositionFFJointTrajectoryActionServerConfig &__getDefault__();
    static const PandaPositionFFJointTrajectoryActionServerConfig &__getMax__();
    static const PandaPositionFFJointTrajectoryActionServerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PandaPositionFFJointTrajectoryActionServerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<std::string>::clamp(PandaPositionFFJointTrajectoryActionServerConfig &config, const PandaPositionFFJointTrajectoryActionServerConfig &max, const PandaPositionFFJointTrajectoryActionServerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PandaPositionFFJointTrajectoryActionServerConfigStatics
  {
    friend class PandaPositionFFJointTrajectoryActionServerConfig;

    PandaPositionFFJointTrajectoryActionServerConfigStatics()
    {
PandaPositionFFJointTrajectoryActionServerConfig::GroupDescription<PandaPositionFFJointTrajectoryActionServerConfig::DEFAULT, PandaPositionFFJointTrajectoryActionServerConfig> Default("Default", "", 0, 0, true, &PandaPositionFFJointTrajectoryActionServerConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_time = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_time = 120.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_time = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("goal_time", "double", 0, "Amount of time (s) controller is permitted to be late achieving goal", "", &PandaPositionFFJointTrajectoryActionServerConfig::goal_time)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("goal_time", "double", 0, "Amount of time (s) controller is permitted to be late achieving goal", "", &PandaPositionFFJointTrajectoryActionServerConfig::goal_time)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stopped_velocity_tolerance = -1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stopped_velocity_tolerance = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stopped_velocity_tolerance = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("stopped_velocity_tolerance", "double", 0, "Maximum velocity (m/s) at end of trajectory to be considered stopped", "", &PandaPositionFFJointTrajectoryActionServerConfig::stopped_velocity_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("stopped_velocity_tolerance", "double", 0, "Maximum velocity (m/s) at end of trajectory to be considered stopped", "", &PandaPositionFFJointTrajectoryActionServerConfig::stopped_velocity_tolerance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint1_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint1_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint1_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint1_goal", "double", 0, "panda_joint1 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint1_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint1_goal", "double", 0, "panda_joint1 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint1_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint2_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint2_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint2_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint2_goal", "double", 0, "panda_joint2 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint2_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint2_goal", "double", 0, "panda_joint2 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint2_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint3_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint3_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint3_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint3_goal", "double", 0, "panda_joint3 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint3_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint3_goal", "double", 0, "panda_joint3 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint3_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint4_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint4_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint4_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint4_goal", "double", 0, "panda_joint4 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint4_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint4_goal", "double", 0, "panda_joint4 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint4_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint5_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint5_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint5_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint5_goal", "double", 0, "panda_joint5 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint5_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint5_goal", "double", 0, "panda_joint5 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint5_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint6_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint6_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint6_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint6_goal", "double", 0, "panda_joint6 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint6_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint6_goal", "double", 0, "panda_joint6 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint6_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint7_goal = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint7_goal = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint7_goal = -0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint7_goal", "double", 0, "panda_joint7 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint7_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint7_goal", "double", 0, "panda_joint7 - maximum final error", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint7_goal)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint1_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint1_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint1_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint1_trajectory", "double", 0, "panda_joint1 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint1_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint1_trajectory", "double", 0, "panda_joint1 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint1_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint2_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint2_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint2_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint2_trajectory", "double", 0, "panda_joint2 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint2_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint2_trajectory", "double", 0, "panda_joint2 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint2_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint3_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint3_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint3_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint3_trajectory", "double", 0, "panda_joint3 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint3_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint3_trajectory", "double", 0, "panda_joint3 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint3_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint4_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint4_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint4_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint4_trajectory", "double", 0, "panda_joint4 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint4_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint4_trajectory", "double", 0, "panda_joint4 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint4_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint5_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint5_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint5_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint5_trajectory", "double", 0, "panda_joint5 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint5_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint5_trajectory", "double", 0, "panda_joint5 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint5_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint6_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint6_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint6_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint6_trajectory", "double", 0, "panda_joint6 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint6_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint6_trajectory", "double", 0, "panda_joint6 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint6_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.panda_joint7_trajectory = -0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.panda_joint7_trajectory = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.panda_joint7_trajectory = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint7_trajectory", "double", 0, "panda_joint7 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint7_trajectory)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::ParamDescription<double>("panda_joint7_trajectory", "double", 0, "panda_joint7 - maximum error during trajectory execution", "", &PandaPositionFFJointTrajectoryActionServerConfig::panda_joint7_trajectory)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PandaPositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr(new PandaPositionFFJointTrajectoryActionServerConfig::GroupDescription<PandaPositionFFJointTrajectoryActionServerConfig::DEFAULT, PandaPositionFFJointTrajectoryActionServerConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PandaPositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PandaPositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PandaPositionFFJointTrajectoryActionServerConfig __max__;
    PandaPositionFFJointTrajectoryActionServerConfig __min__;
    PandaPositionFFJointTrajectoryActionServerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PandaPositionFFJointTrajectoryActionServerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PandaPositionFFJointTrajectoryActionServerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PandaPositionFFJointTrajectoryActionServerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PandaPositionFFJointTrajectoryActionServerConfig &PandaPositionFFJointTrajectoryActionServerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PandaPositionFFJointTrajectoryActionServerConfig &PandaPositionFFJointTrajectoryActionServerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PandaPositionFFJointTrajectoryActionServerConfig &PandaPositionFFJointTrajectoryActionServerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PandaPositionFFJointTrajectoryActionServerConfig::AbstractParamDescriptionConstPtr> &PandaPositionFFJointTrajectoryActionServerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PandaPositionFFJointTrajectoryActionServerConfig::AbstractGroupDescriptionConstPtr> &PandaPositionFFJointTrajectoryActionServerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PandaPositionFFJointTrajectoryActionServerConfigStatics *PandaPositionFFJointTrajectoryActionServerConfig::__get_statics__()
  {
    const static PandaPositionFFJointTrajectoryActionServerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PandaPositionFFJointTrajectoryActionServerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PANDAPOSITIONFFJOINTTRAJECTORYACTIONSERVERRECONFIGURATOR_H__
