// Generated by gencpp from file franka_core_msgs/JointLimits.msg
// DO NOT EDIT!


#ifndef FRANKA_CORE_MSGS_MESSAGE_JOINTLIMITS_H
#define FRANKA_CORE_MSGS_MESSAGE_JOINTLIMITS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_core_msgs
{
template <class ContainerAllocator>
struct JointLimits_
{
  typedef JointLimits_<ContainerAllocator> Type;

  JointLimits_()
    : joint_names()
    , position_lower()
    , position_upper()
    , velocity()
    , accel()
    , effort()  {
    }
  JointLimits_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , position_lower(_alloc)
    , position_upper(_alloc)
    , velocity(_alloc)
    , accel(_alloc)
    , effort(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _position_lower_type;
  _position_lower_type position_lower;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _position_upper_type;
  _position_upper_type position_upper;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocity_type;
  _velocity_type velocity;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _accel_type;
  _accel_type accel;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::franka_core_msgs::JointLimits_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_core_msgs::JointLimits_<ContainerAllocator> const> ConstPtr;

}; // struct JointLimits_

typedef ::franka_core_msgs::JointLimits_<std::allocator<void> > JointLimits;

typedef boost::shared_ptr< ::franka_core_msgs::JointLimits > JointLimitsPtr;
typedef boost::shared_ptr< ::franka_core_msgs::JointLimits const> JointLimitsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_core_msgs::JointLimits_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_core_msgs::JointLimits_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_core_msgs::JointLimits_<ContainerAllocator1> & lhs, const ::franka_core_msgs::JointLimits_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.position_lower == rhs.position_lower &&
    lhs.position_upper == rhs.position_upper &&
    lhs.velocity == rhs.velocity &&
    lhs.accel == rhs.accel &&
    lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_core_msgs::JointLimits_<ContainerAllocator1> & lhs, const ::franka_core_msgs::JointLimits_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_core_msgs::JointLimits_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_core_msgs::JointLimits_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_core_msgs::JointLimits_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4c445eb2c9324525a704c84ca1e7598";
  }

  static const char* value(const ::franka_core_msgs::JointLimits_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4c445eb2c932452ULL;
  static const uint64_t static_value2 = 0x5a704c84ca1e7598ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_core_msgs/JointLimits";
  }

  static const char* value(const ::franka_core_msgs::JointLimits_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# names of the joints\n"
"string[] joint_names\n"
"\n"
"# lower bound on the angular position in radians\n"
"float64[] position_lower\n"
"\n"
"# upper bound on the angular position in radians\n"
"float64[] position_upper\n"
"\n"
"# symmetric maximum joint velocity in radians/second\n"
"float64[] velocity\n"
"\n"
"# symmetric maximum joint acceleration in radians/second^2\n"
"float64[] accel\n"
"\n"
"# symmetric maximum joint torque in Newton-meters\n"
"float64[] effort\n"
;
  }

  static const char* value(const ::franka_core_msgs::JointLimits_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.position_lower);
      stream.next(m.position_upper);
      stream.next(m.velocity);
      stream.next(m.accel);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointLimits_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_core_msgs::JointLimits_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_core_msgs::JointLimits_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "position_lower[]" << std::endl;
    for (size_t i = 0; i < v.position_lower.size(); ++i)
    {
      s << indent << "  position_lower[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position_lower[i]);
    }
    s << indent << "position_upper[]" << std::endl;
    for (size_t i = 0; i < v.position_upper.size(); ++i)
    {
      s << indent << "  position_upper[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position_upper[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
    s << indent << "accel[]" << std::endl;
    for (size_t i = 0; i < v.accel.size(); ++i)
    {
      s << indent << "  accel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.accel[i]);
    }
    s << indent << "effort[]" << std::endl;
    for (size_t i = 0; i < v.effort.size(); ++i)
    {
      s << indent << "  effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.effort[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_CORE_MSGS_MESSAGE_JOINTLIMITS_H
